### ISSUE TITLE
Missing Cc field in email header

### ISSUE THREAD

**Issue by pled** [spymastermatt/thunderbird-monterail#15]
In the header, I can see only 'To' addresses field. When some people are in Cc (copy), they are not displayed.

**Comment by FerSabGar** [comment]
Hi,
I 'creative' solution I found for it was to set as 'default' the 'display' in #expandedHeader2Rows in order to activate the writing of 'cc:' and 'bcc:' fields and also add additional code to print in blue the 'cc:' values and in red the 'bcc:' values in order to avoid incluiding labels for these fields.
So my changes in the code are:

#expandedHeader2Rows row {
	padding-left:15px !important;
	display: default !important; /* before none */

#expandedccBox .headerValue {
	color: blue !important;
}

#expandedbccBox .headerValue {
	color: red !important;
}

Maybe somebody could be it useful. For me it is important to be able to see 'cc:' and 'bcc:' fields.

Thanks to spymastermatt for his excellent work.

**Comment by FerSabGar** [comment]
Finally I could correct the misplacement of the 'from:' field after having enabled the 'cc:' and 'bcc:' fields.
It is necessary enable the 'inline' for display regarding of hearder first part row (#expandedHeaderRows). The code to include is (I put it just before the "#expandedHeader2Rows row {" structure):

#expandedHeaderRows row {
	display: inline !important; 
}

In this way the hearder is perfect, also showing 'cc:' and 'bcc:' fields.

**Comment by spymastermatt** [comment]
Thanks for your help @FerSabGar I have now committed a fix (based off of yours :) ) to my development branch.
Sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues (including this one)

**Comment by FerSabGar** [comment]
Great, @spymastermatt !!!
Thanks for your work.

**Comment by spymastermatt** [comment]
Hi everyone.
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!
