### ISSUE TITLE
Theme monterail problem CSS

### ISSUE THREAD

**Issue by wanderleihuttel** [spymastermatt/thunderbird-monterail#26]
Hello @spymastermatt! I've just get the new version but it look have some wrong CSS in menu option, and the color when an email is active could be the same of select folder tree.

![monterail](https://cloud.githubusercontent.com/assets/16232272/25720063/e5c1a210-30e1-11e7-9c45-c4000039e0bf.png)

Regards
Wanderlei

**Comment by spymastermatt** [comment]
@wanderleihuttel Thanks for spotting this. It looks like Windows puts the menu in a different place to Linux so the color doesn't work. I'll add a check for Windows to fix this.

Regarding the highlight color, they could be the same but as that's a matter of user preference, I'll let you set that in the userChrome.css variables.

Adjust: *--tree-row-highlight-background-color* to be the desired highlight color and then uncomment *--folder-tree-highlight-background-color* and *--message-list-highlight-background-color* so that they use your specified color.

In case you want them, the monterail folder-list highlight color is #3C818F and the message-list highlight color is #B2F2FF

**Comment by spymastermatt** [comment]
@wanderleihuttel Try now, hopefully it should be fixed.

**Comment by wanderleihuttel** [comment]
Hello @spymastermatt !

Now it worked! But when I create a new mail is getting the color os background of  folders.
![monterail2](https://cloud.githubusercontent.com/assets/16232272/25721759/06240eca-30e8-11e7-8cac-01be2c988553.png)

Congratulations for this great job.

There is some place that I could learn about theme thunderbird?

Regards
Wanderlei

**Comment by spymastermatt** [comment]
@wanderleihuttel try again now. I realised only the navigation toolbox wanted changing and have updated it as such.

Regarding theming thunderbird, how much css dow you know?
Other than that you want to install the dom-inspector and element-inspector add-ons.
You also want to check out these two sites:
- https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions - Lists various Mozilla specific css variables and pseudo elements/classes)
- http://www.linnhe2.free-online.co.uk/thunderbird/chrome.html - For a very comprehensive guide to userChrome.css 

If you need any help, please comment on this bug (since it's closed) and I'll be happy to offer any advice I can (though I admit I'm a novice at this myself)
