### ISSUE TITLE
Wrong text color in search box 

### ISSUE THREAD

**Issue by lupa18** [spymastermatt/thunderbird-monterail#55]
Hello,
I'm using fulldark and it seems to be something wrong with text color and search box: I can't see the text I write:

![seleccion_395](https://cloud.githubusercontent.com/assets/463429/26499324/2674981a-4200-11e7-952a-473cddb6f57b.png)

**Comment by bserrao** [comment]
I'm getting this issue with monterail and dark themes. I haven't tried the full dark.
Looking at the previous solution i've tried changing the color in tag.css file but nothing changes.

It might be related to GTK Theme, because i tried changing the theme to Adwaita-dark wich changes the input box background to a dark grey and this way i'm able to see the white text. Otherwise the input background box color is set to white and i'm unable to see the text as i'm typing.

Thanks
