### ISSUE TITLE
Tag colors not applied to message list

### ISSUE THREAD

**Issue by Somnambulated** [spymastermatt/thunderbird-monterail#58]
The text nor the background color change based on tags. 

Confirmed the tag color does work with the Monterrail themes uninstalled.

**Comment by spymastermatt** [comment]
Hi @Somnambulated I recently (Monday 29th) pushed a fix for this. Are you using the latest version?

**Comment by Somnambulated** [comment]
Ohp, I did not see that - my mistake, I will get it now :smile:

**Comment by spymastermatt** [comment]
Not a problem. Let me know it works :)

**Comment by Somnambulated** [comment]
You have single-handedly fixed Thunderbird's biggest UI issues.

**Comment by spymastermatt** [comment]
Haha thanks, I'm glad you like it but it's anything but single-handedly. The design itself comes from this incredible mockup:
https://monterail.com/blog/2016/the-power-of-email-clients-why-did-we-redesign-thunderbird?utm_source=Thunderbird&utm_campaign=Dribbble&utm_medium=blogpost%22

Plus I've had a lot of help from people submitting tweaks/fixes and improvements. In fact the fix for this issue actually comes from the amazing @conema. And then there's all the people (like yourself) helping to test and reporting bugs, without whom the theme would forever remain a pet project used only by me. So thanks again for reporting this!
