### ISSUE TITLE
New message text button colors (dark theme) 

### ISSUE THREAD

**Issue by lupa18** [spymastermatt/thunderbird-monterail#59]
As you can see, something is not going right with colors there: 
(I'm using latest github version)

![seleccion_415](https://user-images.githubusercontent.com/463429/26946281-be309058-4c5c-11e7-9941-1049330cf0d8.png)

**Comment by jdreesen** [comment]
It could be improved in monterail theme, too.
(I'm using latest github version)

![monterail](https://user-images.githubusercontent.com/424602/26946907-1ee0aaf8-4c91-11e7-839f-0aac01ca4f7c.png)

**Comment by Darcidride** [comment]
Hi, same issue here with the Dark theme :
![capture du 2017-06-18 16-48-47](https://user-images.githubusercontent.com/8619233/27261573-275bbfb2-5446-11e7-962e-3cba16cebc7c.png)

Version of Thunderbird : Thunderbird 45.8.0
OS : Debian 8.8 Jessie

**Comment by conema** [comment]
Hi @lupa18, @Darcidride 
My new PR should fixes the issues (#68), see also #67 for dark theme.

@jdreesen, your problem is similar, but if we change the color of the background or the color of the text, it will be changed also in the front page (where email are shown). This wouldn't be good looking, I will try to find a solution in the next days.

**Comment by lupa18** [comment]
It works for me ! thanks!!
